version: "3"
services:
  db:
    image: postgres:16
    restart: no
    container_name: secure-todo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: secure-todo-backend
    restart: no
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PGHOST=localhost
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGDATABASE=tododb
      - PGPORT=5432
    command: ["npm", "start"]

volumes:
  dbdata:
